### ISSUE TITLE
recommend a reproduction repo of alphafold2 structure module

### ISSUE THREAD

**Issue by pengzhangzhi** [biolists/folding_tools#12]
Hi. I personally reproduced the structure module of alphafold2, which basically follows the openfold. I simplify the required pkgs and made it runable with pytorch. The code is for educational purpose. Are you interested in including it in this repo?

https://github.com/pengzhangzhi/protein_structure_module_of_AF2

**Comment by pengzhangzhi** [comment]
The code is all tested. : )

**Comment by sokrypton** [comment]
Thanks! We are happy to include it.
