### ISSUE TITLE
Add a "Features" bullet-point

### ISSUE THREAD

**Issue by avilella** [biolists/folding_tools#4]
Hi all,

Thanks for starting this repo, I think it's a great way to have everything going on in one place.

Could I suggest that each entry has a "Feature" bullet-point, which includes key:value pairs like:

```
Method XYZ
- Paper: URL
- Code repo: URL
- Features = Model_input:MSA; Multimers:no
Method ABC
- Paper: URL
- Code repo: URL
- Features = Model_input:pLM; Multimers:yes
```

Something like that. My idea is to contribute to the repo but also have a table format based on features, a bit like the ColabFold tables, e.g. see below:

![image](https://user-images.githubusercontent.com/158007/183378242-9b5565b8-f04e-46e9-b262-266a3e3ad2aa.png)

See a manually-typed table I created in Google Sheets:

![image](https://user-images.githubusercontent.com/158007/183380248-6929b983-e149-46d5-9843-91623ed7a71b.png)

Thanks for considering

**Comment by sacdallago** [comment]
Yes, yesterday @sokrypton and I were deciding how to split the pLM models from the MSA models, this also came up as an option (having some text attribute rather than creating super categories). I've now restyled the page using "tags". Maybe it's too much, but potentially there could be feature: XX tag, e.g. ![](https://img.shields.io/badge/feature-monomer-lightgrey). What do you think?

**Comment by sacdallago** [comment]
I wish it was possible to filter the page by tags, too... That would be sooooooooo helpful

**Comment by avilella** [comment]
With the reformatted README.md, I can now tabulate the tool names with this one-liner:

```
cat README.md | grep -A999999 '\#\#\#\ Predictors' | grep -B999999 '\#\#\#\ Tools' | \
    grep '^\ \ \-\ ' | sed 's/\ \ \-\ //' | csvtk add-header -n Method > /tmp/2.csv
```
See csvtk at https://github.com/shenwei356/csvtk

Then programmatically compare to the current version in Google Sheets. I can programmatically download the Google Sheets table with:

```
tosheets --spreadsheet=1ikiDyS1TcayyFcdfhywSHQCAwjM3IJOwFB7FGKl8wfc -x -s bit.ly/biofold -c A:A -d ',' > /tmp/1.csv
```
See https://github.com/avilella/tosheets

Then compare a vs b with csvtk and xsv:

```
# cat /tmp/1.csv  | csvtk rename2  -F -f "*" -p "(.*)" -r 'a_${1}'  > /tmp/1.tmp
# cat /tmp/2.csv  | csvtk rename2  -F -f "*" -p "(.*)" -r 'b_${1}'  > /tmp/2.tmp
# xsv join  --full 1 /tmp/1.tmp 1 /tmp/2.tmp  | csvtk rename2 -F -f "*" -p "^a_(.*)" -r 'a_${1}' | csvtk rename2 -F -f "*" -p "^b_(.*)" -r 'b_${1}' 
```
See https://github.com/BurntSushi/xsv

This way we can programmatically find changes in the README.md and easily keep the two in sync in the tabular version.

**Comment by sacdallago** [comment]
You could add the CSV'd readme directly back to the repo, small CSVs render well in GitHub: https://github.com/sacdallago/bio_embeddings/blob/develop/examples/use_case_one/annotation_file.csv

**Comment by sacdallago** [comment]
I think we addressed the main point here :) so cllosing for now
