### ISSUE TITLE
Submission of folds and tangentials

### ISSUE THREAD

**Issue by matteoferla** [biolists/folding_tools#7]
I could not spot a way to submit (=shameless advertise one's own) repos, so I am opening an issue for this —please close it if it is not welcome!

**Comment by matteoferla** [comment]
I for one have some repos that aren't full fledged projects, just snippets. Recently, I made a [repo w/ Python snippet](https://github.com/matteoferla/Snippets-for-ColabFold) for things like inspecting the protein name / species composition within a MMSeq2 MSA with Uniprot IDs (and show the photo from Wikipedia of these, for fun). But previously, I made a few notebooks to analyse ColabFold output via PyRosetta ([repo](https://github.com/matteoferla/pyrosetta_help#colabs)). Is any of this worth adding despite being small things?

**Comment by sacdallago** [comment]
Hi @matteoferla , I'm generally speaking a fan of tools :) but we are trying to be super topical/conservative on tools that are tightly connected to folding tools. So, while I find your first suggestion personally cool, the topic may be too broad for the folidng MD file. @sokrypton Feel free to disagree!

Regarding your second tool, it seems topical to me. Feel free to add it to https://github.com/sacdallago/folding_tools#tools-and-extensions through a pull request!
