### ISSUE TITLE
Long term strategy

### ISSUE THREAD

**Issue by sacdallago** [biolists/folding_tools#9]
Since this repo is now addressing multiple topics (folding, design, pLMs), it may make sense to:

1. Have a general README that redirects to the various sub-lists
2. Transfer this repo to an agnostic organization (for this purpose I prospectively created https://github.com/biolists) so that it's not "sacdallago" who owns it -- but the community
3. Fork into that org other lists, past or future, e.g. @yangkky 's Machine learning for proteins: https://github.com/yangkky/Machine-learning-for-proteins

CC @sokrypton @duerrsimon @noeliaferruz

**Comment by avilella** [comment]
I like the idea, and want to thank all the contributors so far,
with @sacdallago and @sokrypton being the initial instigators on this
folding_tools repo.

It may be worth to mention @amorehead, who started a related repo with some
overlap to this one:
https://github.com/amorehead/awesome-molecular-generation

Bests,

**Comment by noeliaferruz** [comment]
Hey, great idea!

To put the others into context, we (few authors including @sacdallago and myself) were writing a manuscript that reviews advances in DL-powered protein design. 

We have a large list of methods categorized in four classes. We plan to put a list in our newly created org: https://github.com/hefeda because we also provide new code.

One of the categories overlaps with @duerrsimon's and Gina's nice list; maybe we can unite forces :). 

I think that having all the different lists in a shared repo would make sense. Perhaps, for now, we can keep completing our separate lists and then import them to https://github.com/biolists?

**Comment by duerrsimon** [comment]
What could potentially also be useful is to make a smarter mechanism for displaying the information.
I have been setting up this database of colab notebooks powered by github actions where all entries reside in separate markdown files and new entries can be reasily added via a webform that directly creates a pull request. 
See https://colab-db.github.io/   and https://colab-db.github.io/submit   and https://github.com/colab-db/colab-db.github.io

This would be easily tailorable for these curated lists too, except that entries could potentially be in multiple lists and everything is a bit more interactive than plain github where one could search, interactively update star counts etc. We are still developing the database (in particular we want to add validation of the markdown files using pydantic to automatically get information on each pull request if the markdown is valid) but the tech is basically set up and effort to adjust it to the needs of `biolists` would be max a few hours.

**Comment by sacdallago** [comment]
I've done _something_ now :) @duerrsimon that colab DB looks very pretty! However: hours? I don't want to derrail you from doing other important things.

It's my understanding that often these lists arise as a point of "personal frustration" because individuals cannot keep track of things or need to make order in what seems to be an overload of information. Each list is thus a bit different in style and approach, and that's what, IMO, makes them so useful and often unique. The moment you formalize this into a "standard format", you may limit the creativity of an individual in creating their own interpretation of what they want to curate. This is also why I started with a list (flexible, can add "columns" for certain things, not for others,...), but some others prefer tables :)
